name: Deploy

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy repository
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/root/applications/tracker-client"

      - name: Run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /root/applications/tracker-client/streamtracker
            docker compose up --build -d
